### ISSUE TITLE
ecallisto_ng or src.ecallisto_ng

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/ecallisto_ng#2]
If I import the package and want to run the example, I need to replace ecallisto_ng by src.ecallisto_ng

**Comment by ACsillaghy** [comment]
Unfortunately, the trick with "src.ecallisto_ng" does not work. I still cannot execute the notebook. It is still not satisfied with the problem of path to the package, but in a lower module. It needs to work without adding "src"

**Comment by kenfus** [comment]
Did you install it with pip? Usually you should either install the package with pip, from here: https://pypi.org/project/ecallisto-ng/, with `pip install ecallisto_ng` or clone the project and then run `pip install -e ` @ACsillaghy.

**Comment by ACsillaghy** [comment]
Thanks! Now I have installed it with pip. Pip tells me it's already installed. But where? How do I get to the examples? 
Then, I want to work in Pycharm such that I can make corrections (in the texts, no worries). How do I make it work on pycharm?

**Comment by kenfus** [comment]
If you want to make changes, I suggest you cloning the repository, opening it in pycharm and then install it "interactively" with `pip install -e . ` in the terminal inside pycharm (I hope it works the same as VSCode). Then, somewhere you should see the repository locally on your Laptop and you can do changes.
